"""create_timeline_annotations_table

Revision ID: 0eacffe916c8
Revises: 77a77f54047c
Create Date: 2025-08-13 11:14:11.510519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eacffe916c8'
down_revision: Union[str, None] = '77a77f54047c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_timeline_annotations_date_desc', table_name='timeline_annotations')
    op.create_index('ix_timeline_annotations_date_desc', 'timeline_annotations', ['date'], unique=False, postgresql_ops={'date': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_timeline_annotations_date_desc', table_name='timeline_annotations', postgresql_ops={'date': 'DESC'})
    op.create_index('ix_timeline_annotations_date_desc', 'timeline_annotations', [sa.text('date DESC')], unique=False)
    # ### end Alembic commands ###
