"""initial schema

Revision ID: 0ebba5935295
Revises: 
Create Date: 2025-08-26 08:40:12.616750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ebba5935295'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_model_performance',
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('precision', sa.Float(), nullable=True),
    sa.Column('recall', sa.Float(), nullable=True),
    sa.Column('f1_score', sa.Float(), nullable=True),
    sa.Column('training_data_size', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('supabase_user_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('theme', sa.String(length=20), nullable=False),
    sa.Column('auto_categorization_enabled', sa.Boolean(), nullable=False),
    sa.Column('default_items_per_page', sa.Integer(), nullable=False),
    sa.Column('spending_alert_threshold_cents', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_email_active', 'users', ['email', 'is_active'], unique=False)
    op.create_index('idx_user_supabase_id', 'users', ['supabase_user_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_supabase_user_id'), 'users', ['supabase_user_id'], unique=True)
    op.create_table('accounts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=False),
    sa.Column('balance_cents', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('plaid_account_id', sa.String(length=100), nullable=True),
    sa.Column('plaid_access_token_encrypted', sa.Text(), nullable=True),
    sa.Column('plaid_item_id', sa.String(length=100), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('account_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sync_status', sa.String(length=20), nullable=False),
    sa.Column('last_sync_error', sa.Text(), nullable=True),
    sa.Column('connection_health', sa.String(length=20), nullable=False),
    sa.Column('sync_frequency', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plaid_account_id')
    )
    op.create_index('idx_account_plaid_id', 'accounts', ['plaid_account_id'], unique=False)
    op.create_index('idx_account_sync_status', 'accounts', ['sync_status', 'last_sync_at'], unique=False)
    op.create_index('idx_account_type_active', 'accounts', ['account_type', 'is_active'], unique=False)
    op.create_index('idx_account_user_active', 'accounts', ['user_id', 'is_active'], unique=False)
    op.create_table('categories',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('emoji', sa.String(length=10), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_user_category_name')
    )
    op.create_index('idx_category_parent', 'categories', ['parent_id'], unique=False)
    op.create_index('idx_category_system', 'categories', ['is_system'], unique=False)
    op.create_index('idx_category_user_name', 'categories', ['user_id', 'name'], unique=False)
    op.create_table('goals',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('current_amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('goal_type', sa.Enum('SAVINGS', 'DEBT_PAYOFF', 'EMERGENCY_FUND', 'INVESTMENT', 'PURCHASE', 'OTHER', name='goaltype'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='goalpriority'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'PAUSED', 'CANCELLED', name='goalstatus'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('last_contribution_date', sa.Date(), nullable=True),
    sa.Column('monthly_target_cents', sa.BigInteger(), nullable=True),
    sa.Column('celebration_message', sa.Text(), nullable=True),
    sa.Column('milestone_percent', sa.Integer(), nullable=True),
    sa.Column('last_milestone', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_goal_priority_status', 'goals', ['priority', 'status'], unique=False)
    op.create_index('idx_goal_target_date', 'goals', ['target_date'], unique=False)
    op.create_index('idx_goal_user_status', 'goals', ['user_id', 'status'], unique=False)
    op.create_index('idx_goal_user_type', 'goals', ['user_id', 'goal_type'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('BUDGET_ALERT', 'GOAL_MILESTONE', 'GOAL_ACHIEVED', 'GOAL_CREATED', 'GOAL_UPDATED', 'GOAL_DELETED', 'GOAL_STATUS_CHANGED', 'CONTRIBUTION_ADDED', 'TRANSACTION_ALERT', 'LOW_BALANCE_WARNING', 'SYSTEM_ALERT', 'INFO', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('action_url', sa.String(length=512), nullable=True),
    sa.Column('notification_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notification_created', 'notifications', ['created_at'], unique=False)
    op.create_index('idx_notification_user_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_index('idx_notification_user_type', 'notifications', ['user_id', 'type'], unique=False)
    op.create_table('user_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_token', sa.String(length=255), nullable=False),
    sa.Column('device_info', sa.String(length=255), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_activity', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_session_token'), 'user_sessions', ['session_token'], unique=True)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('budgets',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('period', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'YEARLY', name='budgetperiod'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('alert_threshold', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('alert_threshold >= 0.0 AND alert_threshold <= 1.0', name='check_alert_threshold_range'),
    sa.CheckConstraint('amount_cents > 0', name='check_positive_amount'),
    sa.CheckConstraint('end_date IS NULL OR end_date >= start_date', name='check_valid_date_range'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', 'period', name='uq_budget_user_name_period')
    )
    op.create_index('idx_budget_category_active', 'budgets', ['category_id', 'is_active'], unique=False)
    op.create_index('idx_budget_date_range', 'budgets', ['start_date', 'end_date'], unique=False)
    op.create_index('idx_budget_user_active', 'budgets', ['user_id', 'is_active'], unique=False)
    op.create_index('idx_budget_user_category_period', 'budgets', ['user_id', 'category_id', 'period'], unique=False)
    op.create_index('idx_budget_user_period', 'budgets', ['user_id', 'period'], unique=False)
    op.create_table('goal_milestones',
    sa.Column('goal_id', sa.UUID(), nullable=False),
    sa.Column('percentage', sa.Integer(), nullable=False),
    sa.Column('amount_reached_cents', sa.BigInteger(), nullable=False),
    sa.Column('reached_date', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_milestone_goal_percentage', 'goal_milestones', ['goal_id', 'percentage'], unique=False)
    op.create_index('idx_milestone_reached_date', 'goal_milestones', ['reached_date'], unique=False)
    op.create_table('transactions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('merchant', sa.String(length=200), nullable=True),
    sa.Column('merchant_logo', sa.Text(), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('authorized_date', sa.Date(), nullable=True),
    sa.Column('posted_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_transfer', sa.Boolean(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('location', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('plaid_transaction_id', sa.String(length=100), nullable=True),
    sa.Column('plaid_category', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('ml_suggested_category_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['ml_suggested_category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plaid_transaction_id')
    )
    op.create_index('idx_transaction_account_date', 'transactions', ['account_id', 'transaction_date'], unique=False)
    op.create_index('idx_transaction_amount', 'transactions', ['amount_cents'], unique=False)
    op.create_index('idx_transaction_category', 'transactions', ['category_id'], unique=False)
    op.create_index('idx_transaction_merchant', 'transactions', ['merchant'], unique=False)
    op.create_index('idx_transaction_plaid_id', 'transactions', ['plaid_transaction_id'], unique=False)
    op.create_index('idx_transaction_status', 'transactions', ['status'], unique=False)
    op.create_index('idx_transaction_user_date', 'transactions', ['user_id', 'transaction_date'], unique=False)
    op.create_table('budget_alert_settings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('budget_id', sa.UUID(), nullable=True),
    sa.Column('alert_name', sa.String(length=100), nullable=False),
    sa.Column('threshold_percentage', sa.Float(), nullable=False),
    sa.Column('in_app_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('repeat_frequency', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_budget_alert_active', 'budget_alert_settings', ['is_active'], unique=False)
    op.create_index('idx_budget_alert_budget', 'budget_alert_settings', ['budget_id'], unique=False)
    op.create_index('idx_budget_alert_threshold', 'budget_alert_settings', ['threshold_percentage'], unique=False)
    op.create_index('idx_budget_alert_user', 'budget_alert_settings', ['user_id'], unique=False)
    op.create_table('goal_contributions',
    sa.Column('goal_id', sa.UUID(), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('contribution_date', sa.Date(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_contribution_goal_date', 'goal_contributions', ['goal_id', 'contribution_date'], unique=False)
    op.create_index('idx_contribution_transaction', 'goal_contributions', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_contribution_transaction', table_name='goal_contributions')
    op.drop_index('idx_contribution_goal_date', table_name='goal_contributions')
    op.drop_table('goal_contributions')
    op.drop_index('idx_budget_alert_user', table_name='budget_alert_settings')
    op.drop_index('idx_budget_alert_threshold', table_name='budget_alert_settings')
    op.drop_index('idx_budget_alert_budget', table_name='budget_alert_settings')
    op.drop_index('idx_budget_alert_active', table_name='budget_alert_settings')
    op.drop_table('budget_alert_settings')
    op.drop_index('idx_transaction_user_date', table_name='transactions')
    op.drop_index('idx_transaction_status', table_name='transactions')
    op.drop_index('idx_transaction_plaid_id', table_name='transactions')
    op.drop_index('idx_transaction_merchant', table_name='transactions')
    op.drop_index('idx_transaction_category', table_name='transactions')
    op.drop_index('idx_transaction_amount', table_name='transactions')
    op.drop_index('idx_transaction_account_date', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('idx_milestone_reached_date', table_name='goal_milestones')
    op.drop_index('idx_milestone_goal_percentage', table_name='goal_milestones')
    op.drop_table('goal_milestones')
    op.drop_index('idx_budget_user_period', table_name='budgets')
    op.drop_index('idx_budget_user_category_period', table_name='budgets')
    op.drop_index('idx_budget_user_active', table_name='budgets')
    op.drop_index('idx_budget_date_range', table_name='budgets')
    op.drop_index('idx_budget_category_active', table_name='budgets')
    op.drop_table('budgets')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_session_token'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index('idx_notification_user_type', table_name='notifications')
    op.drop_index('idx_notification_user_read', table_name='notifications')
    op.drop_index('idx_notification_created', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('idx_goal_user_type', table_name='goals')
    op.drop_index('idx_goal_user_status', table_name='goals')
    op.drop_index('idx_goal_target_date', table_name='goals')
    op.drop_index('idx_goal_priority_status', table_name='goals')
    op.drop_table('goals')
    op.drop_index('idx_category_user_name', table_name='categories')
    op.drop_index('idx_category_system', table_name='categories')
    op.drop_index('idx_category_parent', table_name='categories')
    op.drop_table('categories')
    op.drop_index('idx_account_user_active', table_name='accounts')
    op.drop_index('idx_account_type_active', table_name='accounts')
    op.drop_index('idx_account_sync_status', table_name='accounts')
    op.drop_index('idx_account_plaid_id', table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_users_supabase_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_user_supabase_id', table_name='users')
    op.drop_index('idx_user_email_active', table_name='users')
    op.drop_table('users')
    op.drop_table('ml_model_performance')
    # ### end Alembic commands ###
