"""create_saved_filters_table

Revision ID: 3adf66499bc9
Revises: 0eacffe916c8
Create Date: 2025-08-13 11:37:49.258668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3adf66499bc9'
down_revision: Union[str, None] = '0eacffe916c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_timeline_annotations_date_desc', table_name='timeline_annotations')
    op.create_index('ix_timeline_annotations_date_desc', 'timeline_annotations', ['date'], unique=False, postgresql_ops={'date': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_timeline_annotations_date_desc', table_name='timeline_annotations', postgresql_ops={'date': 'DESC'})
    op.create_index('ix_timeline_annotations_date_desc', 'timeline_annotations', [sa.text('date DESC')], unique=False)
    # ### end Alembic commands ###
