"""Update user_preferences low_balance_threshold to cents

Revision ID: 4c48d9ea50e0
Revises: a14c635fd29a
Create Date: 2025-08-15 09:03:16.970925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c48d9ea50e0'
down_revision: Union[str, None] = 'a14c635fd29a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_timeline_annotations_date_desc', table_name='timeline_annotations')
    op.create_index('ix_timeline_annotations_date_desc', 'timeline_annotations', ['date'], unique=False, postgresql_ops={'date': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_timeline_annotations_date_desc', table_name='timeline_annotations', postgresql_ops={'date': 'DESC'})
    op.create_index('ix_timeline_annotations_date_desc', 'timeline_annotations', [sa.text('date DESC')], unique=False)
    # ### end Alembic commands ###
