"""add_user_preference_fields

Revision ID: 668eebd3c250
Revises: b4e49890e5ec
Create Date: 2025-08-24 06:33:40.826813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '668eebd3c250'
down_revision: Union[str, None] = 'b4e49890e5ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns with default values for existing users
    op.add_column('users', sa.Column('default_items_per_page', sa.Integer(), nullable=False, server_default='25'))
    op.add_column('users', sa.Column('auto_categorization_enabled', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('users', sa.Column('spending_alert_threshold_cents', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'spending_alert_threshold_cents')
    op.drop_column('users', 'auto_categorization_enabled')
    op.drop_column('users', 'default_items_per_page')
    # ### end Alembic commands ###
