"""create_user_preferences_table

Revision ID: a14c635fd29a
Revises: 94609d563151
Create Date: 2025-08-14 19:36:59.347228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a14c635fd29a'
down_revision: Union[str, None] = '94609d563151'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_timeline_annotations_date_desc', table_name='timeline_annotations')
    op.create_index('ix_timeline_annotations_date_desc', 'timeline_annotations', ['date'], unique=False, postgresql_ops={'date': 'DESC'})
    op.drop_index('idx_user_sessions_active', table_name='user_sessions')
    op.drop_index('idx_user_sessions_last_activity', table_name='user_sessions')
    op.drop_index('idx_user_sessions_token', table_name='user_sessions')
    op.drop_index('idx_user_sessions_user_id', table_name='user_sessions')
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.create_index('idx_user_sessions_user_id', 'user_sessions', ['user_id'], unique=False)
    op.create_index('idx_user_sessions_token', 'user_sessions', ['session_token'], unique=False)
    op.create_index('idx_user_sessions_last_activity', 'user_sessions', ['last_activity'], unique=False)
    op.create_index('idx_user_sessions_active', 'user_sessions', ['user_id', 'is_active'], unique=False)
    op.drop_index('ix_timeline_annotations_date_desc', table_name='timeline_annotations', postgresql_ops={'date': 'DESC'})
    op.create_index('ix_timeline_annotations_date_desc', 'timeline_annotations', [sa.text('date DESC')], unique=False)
    # ### end Alembic commands ###
